CREATE TABLE VISIT_DVOA_data (
	VISIT_Team VARCHAR,
	Year int,
	Week int,
	Opponent VARCHAR,
	VISIT_TotalDVOA DEC,
	VISIT_OffenseDVOA DEC,
	VISIT_OffPassDVOA DEC,
	VISIT_OffRushDVOA DEC,
	VISIT_DefenseDVOA DEC,
	VISIT_DefPassDVOA DEC,
	VISIT_DefRushDVOA DEC,
	VISIT_STDVOA DEC
);