CREATE TABLE HOME_DVOA_data (
	HOME_Team VARCHAR,
	Year int,
	Week int,
	Opponent VARCHAR,
	HOME_TotalDVOA DEC,
	HOME_OffenseDVOA DEC,
	HOME_OffPassDVOA DEC,
	HOME_OffRushDVOA DEC,
	HOME_DefenseDVOA DEC,
	HOME_DefPassDVOA DEC,
	HOME_DefRushDVOA DEC,
	HOME_STDVOA DEC
);